version: "3"
services:
  kb_front:
    container_name: kb_front
    image: logotipiwe/kb_front:2
#    build: .
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dc-net
networks:
  dc-net:
    external: true