name: Front CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: Logotipiwe/dc_vars
        token: ${{secrets.PAT}}
    - name: load-env
      uses: duskmoon314/action-load-env@v1.1.0

    - name: Checkout project
      uses: actions/checkout@v3
      with:
        repository: Logotipiwe/dc_kb_front
        token: ${{secrets.PAT}}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ env.DOCKER_PAT }}
    - name: Build
      id: build_push
      run: |
        ls
        export KB_FRONT_IMAGE=${{ env.DOCKER_USER }}/kb_front:$(date +%s)
        docker build . -t ${KB_FRONT_IMAGE}
        docker push ${KB_FRONT_IMAGE}
        echo "KB_FRONT_IMAGE=${KB_FRONT_IMAGE}" >> "$GITHUB_ENV"
    - name: Upload
      uses: garygrossgarten/github-action-scp@release
      with:
        local: kb_front.yml
        concurrency: 20
        remote: /kuber/kb_front/kb_front.yml
        host: ${{ env.DC_HOST }}
        username: ${{ env.SSH_USER }}
        password: ${{ env.SSH_PASSWORD }}
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ env.DC_HOST }}
        username: ${{ env.SSH_USER }}
        password: ${{ env.SSH_PASSWORD }}
        port: 22
        script: |
          export KB_FRONT_IMAGE=${{ env.KB_FRONT_IMAGE }}
          docker-compose -f /kuber/kb_front/kb_front.yml down --remove-orphans
          docker-compose -f /kuber/kb_front/kb_front.yml up -d